DB_URL=jdbc:mysql://localhost:3306/gate_prediction?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
DB_USERNAME=root
DB_PASSWORD=vishnu24265A0509

JWT_SECRET=gate_prediction_super_secret_key_2024_vishnu_project


GEMINI_API_KEY=AIzaSyBKHfA6enzU0UFn4gfACpGt5O9fahDWJr0
